version: "3.4"

services:
    
    gym_php:
        image: php:testebd
        volumes:
            - type: bind
              source: ./
              target: /var/www/html
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                order: start-first
        networks:
            es2_default:
                aliases:
                    - gym_php
    gym_nginx:
        image: nginx:1.11.8
        ports:
            - "8080:80"
        volumes:
            - type: bind
              source: .
              target: /var/www/html
            - type: bind
              source: ./logs
              target: /var/log/nginx/
            - type: bind
              source: ./nginx/default.conf
              target: /etc/nginx/conf.d/default.conf
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                delay: 15s
                parallelism: 1
                order: start-first
        networks:
            es2_default:
                aliases:
                    - gym_nginx
    mysql:
        image: mysql:5.7.20
        volumes:
            - type: bind
              source: ./data
              target: /var/lib/mysql
        ports:
            - "3307:3306"
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
networks:
    es2_default:
        external: true
